import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, "..");

await build({
	entryPoints: [path.join(ROOT_DIR, "server/index.ts")],
	bundle: true,
	platform: "node",
	target: "node22",
	format: "esm",
	outfile: path.join(ROOT_DIR, "dist/server.js"),
	// Mark production dependencies as external — they are installed in Docker
	external: ["fastify", "@fastify/http-proxy", "@fastify/static", "@nycu-sdc/core-system-sdk", "undici"],
	alias: {
		"@": path.join(ROOT_DIR, "src")
	},
	banner: {
		js: "// Auto-generated by scripts/build-server.mjs — do not edit"
	}
});

console.log("✓ Server bundled to dist/server.js");
